### PR TITLE
commands.py: Pass number to tab()

### PR DESCRIPTION
**Pull request by nfnty**
shift-tab functionality for scout etc.

### CODE REVIEW

**Comment by hut** [comment]
This would break every custom commands.py for a feature nobody asked for, even though I guess it makes sense to have this. Not sure what to do, maybe I can think of a cleaner way to add this fuctionality.

**Comment by hut** [comment]
Some options:
* add a function called `tab_shift`
* add an attribute called `self.shift_pressed` (probably a bad idea because of unnecessary statefulness)

**Comment by nfnty** [comment]
Fixed it by inspecting `tab()` arguments before calling it.

**Comment by hut** [comment]
That's an elegant solution, but I wonder if it might confuse the users. In standard python, it never happens that you can override methods with different numbers of arguments, unless you use *args or **kwargs. At least I haven't ever seen it. Either way, I'll merge it. Most likely, nobody will ever perceive this as an issue. :D

**Comment by hut** [comment]
Wait, IMO tabnum is kind of counterintuitive. How about using tab(self, shift=True/False) instead?

**Comment by nfnty** [comment]
With tabnum you can bind shift to any size. I.e. `cmap <C-TAB> eval fm.ui.console.tab(-5)`

**Comment by nfnty** [comment]
Rebased to master.

**Pull request merged**
