### PR TITLE
make mv/cp generators yield progress

### PR DESCRIPTION
**Pull request by notEvil**
a small patch to `CopyLoader` which would allow more flexible plugins (e.g. do mv/cp in elevated subprocess using some custom Loader for progress update)

### CODE REVIEW

**Comment by hut** [comment]
Looks good, thanks :)

**Comment by notEvil** [comment]
Thx :)
just realized that `import time` in ranger/ext/shutil_generatorized.py is not necessary. My mistake

**Comment by hut** [comment]
I removed it, thanks ^^

**Comment by hut** [comment]
Actually, this breaks the progress bar when copying multiple files at once. Can you please take a look at the problem?

**Comment by notEvil** [comment]
you are right. a few lines were missing. with the new commit it should be fixed. should I create a new pull request?

**Comment by hut** [comment]
Nope, it's fine :) thanks!

**Pull request merged**
