### PR TITLE
Added cmap for forward word deletion.

### PR DESCRIPTION
**Pull request by NoSuck**
The `<C-delete>` shortcut probably won't work with most terminal configs.

### CODE REVIEW

**Comment by hut** [comment]
Is there a terminal that it does work on?

**Comment by NoSuck** [comment]
I don't know.  Is there a way to map [3;5~ in ranger?  Vim can handle it, so I know it's possible...

**Comment by hut** [comment]
ranger can't deal with that mapping. If you want to bind it, you need to extend the keybinding parser and the handle_input method in ranger.gui.ui. Not worth the effort IMO but up to you.

**Comment by NoSuck** [comment]
Eh, I took that part out.  Please accept my puny patch!  It's not the size that counts!

**Comment by hut** [comment]
Sure. Could you squash those commits into 1? I'd do it myself but you may want your name as the author/commiter :p

**Comment by NoSuck** [comment]
Hey, I learned something today.  SQUASHED.

**Comment by hut** [comment]
Thanks. And I didn't even notice that it was your first time ;)

**Pull request merged**
