### PR TITLE
[STUPID+FIXME] Show modification date in main column. Terribly defunct code.

### PR DESCRIPTION
**Pull request by eMPee584**
Not meant for merging.. can this be done better?

### CODE REVIEW

**Comment by hut** [comment]
This sounds like a job for a so-called linemode, see https://github.com/hut/ranger/blob/master/ranger/core/linemode.py

And the example plugin: https://github.com/hut/ranger/blob/master/examples/plugin_linemode.py

**Comment by eMPee584** [comment]
Yes definitely.. I cnoded this before I tripped over the new linemode
implementation. Still didn't quite grok it, the rofl_23 example is a bit
basic :smirk:

**Comment by hut** [comment]
You can add an "infostring" method to your linemode class, like in FileInfoLinemode ( https://github.com/hut/ranger/blob/master/ranger/core/linemode.py#L96 ). There, you can simply return the string you generated with strftime.

**Comment by hut** [comment]
And https://github.com/hut/ranger/wiki/Custom-linemodes

**Pull request closed without merging**
