### PR TITLE
Added toggle mode for cut/copy actions.

### PR DESCRIPTION
**Pull request by NoSuck**
Toggling is handy.

### CODE REVIEW

**Comment by hut** [comment]
thanks

**Comment by lamarpavel** [comment]
Based on the code I can't tell what exactly this is doing, could you please also add a short description to the manpage?

**Comment by hut** [comment]
@lamarpavel Explained in b6be66e8851f6b2b775eec2782e83af8340bfba0

**Comment by NoSuck** [comment]
Ah, I didn't realize there was a description of mode in there.  Thanks, hut.

**Pull request merged**
