### PR TITLE
Add an alternative highlight function

### PR DESCRIPTION
**Pull request by Vifon**
I've moved the highlight-specific arguments inside our wrapper and added an alternative one using pygments.

### CODE REVIEW

**Comment by hut** [comment]
How about generalizing the highlight function to a generic "protect any command from sigpipes"-function? We could then use it for both highlight and pygmentize, and use the usual mechanism with the try/dump functions to determine which one should be started.

**Comment by Vifon** [comment]
Like this?

**Comment by hut** [comment]
Like 9f87b7d3a7374f369f0c04bd3758cc9da7a2a67b

**Comment by hut** [comment]
My last attempt was incorrect, as you explained on IRC. Does 82ae8743adf352387dd1f3996af1dbe5a25a02a3 sound fine?

**Comment by Vifon** [comment]
Looks good to me.

**Comment by hut** [comment]
Merged

**Pull request closed without merging**
