### PR TITLE
add line numbers in main column

### PR DESCRIPTION
**Pull request by mrogalski**
As requested in #489, add line numbers in main column.  Supports normal and relative variants.

### CODE REVIEW

**Comment by hut** [comment]
Thanks, this has been long awaited by many people!

I changed your patch in e01bf0062ad29f356878985a813b47ec86966803 so it only uses 1 option, `line_numbers={false,absolute,relative}` rather than two.

**Comment by mrogalski** [comment]
No worries, I really missed this from vim.  
A'propos changing this file, could You please look at these two lines?
https://github.com/hut/ranger/blob/30cf3e0d640e7ea35c1268cfa871004dacd9e856/ranger/gui/widgets/browsercolumn.py#L261-L262

Are they really necessary?  I mean, the loop is `for line in range(self.hei):`,  so `line` should always be smaller than `self.hei`... unless I am missing something.
You have introduced this in 5417dda5fcb4950cb8979e311ae29d285615a633.

**Comment by hut** [comment]
Yep, those lines seem to be redundant. Don't know why I added them. Want to send a PR to get the credit, or should I patch this?

**Comment by mrogalski** [comment]
Made the PR just to get a pointless little green badge to feel like achieving something: hut/ranger#556 :)

**Pull request merged**
